CREATE TABLE `scouting_reports` (
	`id` text PRIMARY KEY NOT NULL,
	`player_id` text NOT NULL,
	`scouted_by` text,
	`last_watched_date` text,
	`summary` text,
	`tactical_vision` text,
	`finishing` text,
	`finding_space` text,
	`passing` text,
	`dribbling` text,
	`organisation` text,
	`tackling` text,
	`pressing_opposition` text,
	`head_game` text,
	`cover_full_back` text,
	`communication` text,
	`speed` text,
	`pace` text,
	`stamina` text,
	`explosiveness` text,
	`support_play` text,
	`crossing` text,
	`strength` text,
	`durability` text,
	`concentration` text,
	`attitude` text,
	`motivation` text,
	`work_rate` text,
	`leadership` text,
	`composure` text,
	`created_at` text DEFAULT (current_timestamp) NOT NULL,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL,
	FOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `scouting_reports_player_id_unique` ON `scouting_reports` (`player_id`);